-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }
-keep class androidx.camera.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn com.google.mlkit.**
-dontwarn androidx.camera.**
